// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIUV7EpGOhSJc9y40OrImm8xTvfY1JD0',
    appId: '1:904742737185:web:3248d5e7b839150cc19a60',
    messagingSenderId: '904742737185',
    projectId: 'remath-pro',
    authDomain: 'remath-pro.firebaseapp.com',
    storageBucket: 'remath-pro.appspot.com',
    measurementId: 'G-SQ4GYW0GLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-Np_jbILdcfoBrojLi7Qnd4B0Jl1Ap8',
    appId: '1:904742737185:android:2c01a83043eddff1c19a60',
    messagingSenderId: '904742737185',
    projectId: 'remath-pro',
    storageBucket: 'remath-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9fBCean36POl4DWDF8s8jdwNX1m7sZpM',
    appId: '1:904742737185:ios:48c378cc77df182ec19a60',
    messagingSenderId: '904742737185',
    projectId: 'remath-pro',
    storageBucket: 'remath-pro.appspot.com',
    iosBundleId: 'com.example.flutterMathsTricks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9fBCean36POl4DWDF8s8jdwNX1m7sZpM',
    appId: '1:904742737185:ios:48c378cc77df182ec19a60',
    messagingSenderId: '904742737185',
    projectId: 'remath-pro',
    storageBucket: 'remath-pro.appspot.com',
    iosBundleId: 'com.example.flutterMathsTricks',
  );
}
